language: java
jdk:
  - oraclejdk9
sudo: false
before_script:
  - _JAVA_OPTIONS="-Xmx8192m -Xms512m"

script:
  - mvn clean compile assembly:single
  - mvn -Dtest=FrontendTests test
  - mvn -Dtest=RuntimeTests test
  - mvn -Dtest=SparkRuntimeTests test


