site_name: RumbleDB 1.17 "Cacao Tree" beta
pages:
  - '1. Documentation home': 'index.md'
  - '2. Getting started': 'Getting started.md'
  - '3. Run with docker': 'Docker.md'
  - '4. Run on a cluster': 'Run on a cluster.md'
  - '5. Run in Jupyter notebooks (experimental)': 'HTTPServer.md'
  - '6. The JSONiq language': 'JSONiq.md'
  - '7. Reading data': 'Input.md'
  - '8. Function library': 'Function library.md'
  - '9. CLI and HTTP parameters': 'CLI.md'
  - '10. Define and validate your own types': 'Types.md'
  - '11. Machine learning library': 'RumbleML.md'
  - '12. FAQ and common issues': 'FAQ.md'
  - '13. Error codes': 'Error codes.md'
  - '14. Compile from GitHub': 'install.md'
  - '15. Licenses': 'Licenses.md'
theme: readthedocs
